GLOBAL_LIST_INIT(bitfields, list(
	"flags_ammo_behavior" = list(
		"AMMO_EXPLOSIVE" = AMMO_EXPLOSIVE,
		"AMMO_XENO" = AMMO_XENO,
		"AMMO_ENERGY" = AMMO_ENERGY,
		"AMMO_ROCKET" = AMMO_ROCKET,
		"AMMO_SNIPER" = AMMO_SNIPER,
		"AMMO_INCENDIARY" = AMMO_INCENDIARY,
		"AMMO_SKIPS_HUMANS" = AMMO_SKIPS_HUMANS,
		"AMMO_SKIPS_ALIENS" = AMMO_SKIPS_ALIENS,
		"AMMO_IS_SILENCED" = AMMO_IS_SILENCED,
		"AMMO_IGNORE_ARMOR" = AMMO_IGNORE_ARMOR,
		"AMMO_IGNORE_RESIST" = AMMO_IGNORE_RESIST,
		"AMMO_BALLISTIC" = AMMO_BALLISTIC
		)